import sys
#sys.path.insert(0,'/Users/atheisen/Code/sandbox/ACT')
import act
print(act.__file__)
import act.tests.test_retrievals as tr
import act.tests.test_utils as tu
import act.tests.test_correct as tc
import act.tests.test_io as ti
import act.tests.test_plotting as tp
import act.tests.test_qc as tq
import act.tests.test_discovery as td
import matplotlib.pyplot as plt

td.test_get_armfile()
#tu.test_adjust_timestamp()
#tr.test_calculate_heffter_pbl()
#tr.test_calculate_pbl_liu_liang()
#ti.test_read_psl_fmcw_moment()
#td.test_airnow()
#tq.test_qc_flag_description()
#tp.test_plot_datarose()
#td.test_noaa_psl()
#tq.test_bsrn_limits_test()
#ti.test_io_csv()
#tr.test_sp2_psds()
#tp.test_time_plot2()
#tq.test_qcfilter()
#ti.test_read_psl_wind_profiler()
#tp.test_multi_skewt_plot()
#tu.test_height_adjusted_pressure()
#tp.test_2D_timeseries_plot()
#plt.show()

#td.test_get_ord()
#tp.test_contour_stamp()

#tc.test_correct_ceil()
#tp.test_histogram_errors()
#tq.test_qc_test_errors()
#ti.test_io_write()
#tq.test_qctests()
#td.test_cropType()
#ti.test_io()
#tu.test_calculate_dqr_times()
#tu.test_get_sunrise_sunset_noon()
#tp.test_wind_rose()
#td.test_get_armfile()
#tq.test_arm_qc()

#tr.test_calculate_sirs_variable()
#tu.test_planck_converter()
#tu.test_ts_weighted_average()
#tu.test_reduce_time_ranges()
#ti.test_io_anl_csv()
#tc.test_correct_rl()
#tc.test_correct_mpl()
#tp.test_barb_sounding_plot()
#tp.test_errors()
#tp.test_qc_bar_plot()
#tp.test_plot_barbs_from_u_v2()
#plt.show()
#plt.show()
#tq.test_qcfilter()
#tu.test_add_solar_variable()
#tu.test_create_pyart_obj()
#ti.test_io_mpldataset()
#tp.test_xsection_plot_map()
#tp.test_geoplot()
#tq.test_fft_shading_test()
#tr.test_sst()
#tr.test_aeri2irt()
#tp.test_size_distribution()
#tr.test_get_stability_indices()
#tu.test_add_in_nan()
#tu.test_accum_precip()
#tu.test_calc_cog_sog()
#tu.test_calc_cog_sog()
#tc.test_correct_wind()
#ti.test_io_dod()
#tu.test_destination_azimuth_distance()
#ti.test_io_mfdataset()
#tmu.test_get_missing_value()
